'use strict';

exports.categories = [
  {"category_id": 1, "title": "Factual Places"},
  {"category_id": 2, "title": "Automotive"},
  {"category_id": 3, "title": "Car Appraisers"},
  {"category_id": 4, "title": "Car Dealers and Leasing"},
  {"category_id": 5, "title": "Used Cars"},
  {"category_id": 6, "title": "Car Parts and Accessories"},
  {"category_id": 7, "title": "Car Wash and Detail"},
  {"category_id": 8, "title": "Classic and Antique Car"},
  {"category_id": 9, "title": "Maintenance and Repair"},
  {"category_id": 10, "title": "Oil and Lube"},
  {"category_id": 11, "title": "Smog Check"},
  {"category_id": 12, "title": "Tires"},
  {"category_id": 13, "title": "Transmissions"},
  {"category_id": 14, "title": "Motorcycles, Mopeds and Scooters"},
  {"category_id": 15, "title": "Repair"},
  {"category_id": 16, "title": "Sales"},
  {"category_id": 17, "title": "RVs and Motor Homes"},
  {"category_id": 18, "title": "Salvage Yards"},
  {"category_id": 19, "title": "Towing"},
  {"category_id": 20, "title": "Community and Government"},
  {"category_id": 21, "title": "Animal Shelters and Humane Societies"},
  {"category_id": 22, "title": "Cemeteries"},
  {"category_id": 23, "title": "Day Care and Preschools"},
  {"category_id": 24, "title": "Disabled Persons Services"},
  {"category_id": 25, "title": "Drug and Alcohol Services"},
  {"category_id": 26, "title": "Education"},
  {"category_id": 27, "title": "Adult Education"},
  {"category_id": 28, "title": "Art Lessons and Schools"},
  {"category_id": 29, "title": "Colleges and Universities"},
  {"category_id": 30, "title": "Computer Training"},
  {"category_id": 31, "title": "Culinary Lessons and Schools"},
  {"category_id": 32, "title": "Driving Schools"},
  {"category_id": 33, "title": "Fraternities and Sororities"},
  {"category_id": 34, "title": "Primary and Secondary Schools"},
  {"category_id": 35, "title": "Tutoring and Educational Services"},
  {"category_id": 36, "title": "Vocational Schools"},
  {"category_id": 37, "title": "Government Departments and Agencies"},
  {"category_id": 38, "title": "Government Lobbyists"},
  {"category_id": 39, "title": "Housing Assistance and Shelters"},
  {"category_id": 40, "title": "Law Enforcement and Public Safety"},
  {"category_id": 41, "title": "Rescue Services"},
  {"category_id": 42, "title": "Fire Stations"},
  {"category_id": 43, "title": "Police Stations"},
  {"category_id": 44, "title": "Libraries"},
  {"category_id": 45, "title": "Military"},
  {"category_id": 46, "title": "Bases"},
  {"category_id": 47, "title": "Organizations and Associations"},
  {"category_id": 48, "title": "Charities and Non-Profits"},
  {"category_id": 49, "title": "Environmental"},
  {"category_id": 50, "title": "Youth Organizations"},
  {"category_id": 51, "title": "Post Offices"},
  {"category_id": 52, "title": "Public and Social Services"},
  {"category_id": 53, "title": "Religious"},
  {"category_id": 54, "title": "Buddhist Temples"},
  {"category_id": 55, "title": "Churches"},
  {"category_id": 56, "title": "Hindu Temples"},
  {"category_id": 57, "title": "Mosques"},
  {"category_id": 58, "title": "Synagogues"},
  {"category_id": 59, "title": "Senior Citizen Services"},
  {"category_id": 60, "title": "Retirement"},
  {"category_id": 61, "title": "Utility Companies"},
  {"category_id": 62, "title": "Healthcare"},
  {"category_id": 63, "title": "AIDS Resources"},
  {"category_id": 64, "title": "Assisted Living Services"},
  {"category_id": 65, "title": "Home Health Care Services"},
  {"category_id": 66, "title": "Facilities and Nursing Homes"},
  {"category_id": 67, "title": "Blood Banks and Centers"},
  {"category_id": 68, "title": "Chiropractors"},
  {"category_id": 69, "title": "Dentists"},
  {"category_id": 70, "title": "Emergency Services"},
  {"category_id": 71, "title": "Ambulance"},
  {"category_id": 72, "title": "Holistic, Alternative and Naturopathic Medicine"},
  {"category_id": 73, "title": "Acupuncture"},
  {"category_id": 74, "title": "Hospitals, Clinics and Medical Centers"},
  {"category_id": 75, "title": "Medical Supplies and Labs"},
  {"category_id": 76, "title": "Mental Health"},
  {"category_id": 77, "title": "Counseling and Therapy"},
  {"category_id": 78, "title": "Psychologists"},
  {"category_id": 79, "title": "Nurses"},
  {"category_id": 80, "title": "Pharmacies"},
  {"category_id": 81, "title": "Physical Therapy and Rehabilitation"},
  {"category_id": 82, "title": "Sports Medicine"},
  {"category_id": 83, "title": "Physicians"},
  {"category_id": 84, "title": "Anesthesiologists"},
  {"category_id": 85, "title": "Cardiologists"},
  {"category_id": 86, "title": "Dermatologists"},
  {"category_id": 87, "title": "Ear, Nose and Throat"},
  {"category_id": 88, "title": "Family Medicine"},
  {"category_id": 89, "title": "Gastroenterologists"},
  {"category_id": 90, "title": "General Surgery"},
  {"category_id": 91, "title": "Internal Medicine"},
  {"category_id": 92, "title": "Neurologists"},
  {"category_id": 93, "title": "Obstetricians and Gynecologists"},
  {"category_id": 94, "title": "Oncologists"},
  {"category_id": 95, "title": "Ophthalmologists"},
  {"category_id": 96, "title": "Orthopedic Surgeons"},
  {"category_id": 97, "title": "Pathologists"},
  {"category_id": 98, "title": "Pediatricians"},
  {"category_id": 99, "title": "Plastic Surgeons"},
  {"category_id": 100, "title": "Psychiatrists"},
  {"category_id": 101, "title": "Radiologists"},
  {"category_id": 102, "title": "Respiratory"},
  {"category_id": 103, "title": "Urologists"},
  {"category_id": 104, "title": "Podiatrists"},
  {"category_id": 105, "title": "Pregnancy and Sexual Health"},
  {"category_id": 106, "title": "Weight Loss and Nutritionists"},
  {"category_id": 107, "title": "Landmarks"},
  {"category_id": 108, "title": "Buildings and Structures"},
  {"category_id": 109, "title": "Gardens"},
  {"category_id": 110, "title": "Historic and Protected Sites"},
  {"category_id": 111, "title": "Monuments and Memorials"},
  {"category_id": 112, "title": "Natural"},
  {"category_id": 113, "title": "Beaches"},
  {"category_id": 114, "title": "Mountains"},
  {"category_id": 115, "title": "Forests"},
  {"category_id": 116, "title": "Lakes"},
  {"category_id": 117, "title": "Rivers"},
  {"category_id": 118, "title": "Parks"},
  {"category_id": 119, "title": "Natural Parks"},
  {"category_id": 120, "title": "Picnic Areas"},
  {"category_id": 121, "title": "Playgrounds"},
  {"category_id": 122, "title": "Urban Parks"},
  {"category_id": 123, "title": "Retail"},
  {"category_id": 124, "title": "Adult"},
  {"category_id": 125, "title": "Antiques"},
  {"category_id": 126, "title": "Arts and Crafts"},
  {"category_id": 127, "title": "Auctions"},
  {"category_id": 128, "title": "Beauty Products"},
  {"category_id": 129, "title": "Bicycles"},
  {"category_id": 130, "title": "Bookstores"},
  {"category_id": 131, "title": "Cards and Stationery"},
  {"category_id": 132, "title": "Children"},
  {"category_id": 133, "title": "Computers and Electronics"},
  {"category_id": 134, "title": "Cameras"},
  {"category_id": 135, "title": "Mobile Phones"},
  {"category_id": 136, "title": "Video Games"},
  {"category_id": 137, "title": "Construction Supplies"},
  {"category_id": 138, "title": "Convenience Stores"},
  {"category_id": 139, "title": "Costumes"},
  {"category_id": 140, "title": "Dance and Music"},
  {"category_id": 141, "title": "Department Stores"},
  {"category_id": 142, "title": "Fashion"},
  {"category_id": 143, "title": "Clothing and Accessories"},
  {"category_id": 144, "title": "Jewelry and Watches"},
  {"category_id": 145, "title": "Shoes"},
  {"category_id": 146, "title": "Swimwear"},
  {"category_id": 147, "title": "Flea Markets"},
  {"category_id": 148, "title": "Florists"},
  {"category_id": 149, "title": "Food and Beverage"},
  {"category_id": 150, "title": "Beer, Wine and Spirits"},
  {"category_id": 151, "title": "Candy Stores"},
  {"category_id": 152, "title": "Cheese"},
  {"category_id": 153, "title": "Chocolate"},
  {"category_id": 154, "title": "Farmers' Markets"},
  {"category_id": 155, "title": "Health and Diet Food"},
  {"category_id": 156, "title": "Kosher"},
  {"category_id": 157, "title": "Furniture and Decor"},
  {"category_id": 158, "title": "Gift and Novelty"},
  {"category_id": 159, "title": "Glasses"},
  {"category_id": 160, "title": "Hobby and Collectibles"},
  {"category_id": 161, "title": "Luggage"},
  {"category_id": 162, "title": "Music, Video and DVD"},
  {"category_id": 163, "title": "Newsstands"},
  {"category_id": 164, "title": "Nurseries and Garden Centers"},
  {"category_id": 165, "title": "Outlet"},
  {"category_id": 166, "title": "Pawn Shops"},
  {"category_id": 167, "title": "Pets"},
  {"category_id": 168, "title": "Photos and Frames"},
  {"category_id": 169, "title": "Shopping Centers and Malls"},
  {"category_id": 170, "title": "Sporting Goods"},
  {"category_id": 171, "title": "Supermarkets and Groceries"},
  {"category_id": 172, "title": "Tobacco"},
  {"category_id": 173, "title": "Toys"},
  {"category_id": 174, "title": "Vintage and Thrift"},
  {"category_id": 175, "title": "Warehouses and Wholesale Stores"},
  {"category_id": 176, "title": "Wedding and Bridal"},
  {"category_id": 177, "title": "Businesses and Services"},
  {"category_id": 178, "title": "Business and Strategy Consulting"},
  {"category_id": 179, "title": "Industrial Machinery and Vehicles"},
  {"category_id": 180, "title": "Logging and Sawmills"},
  {"category_id": 181, "title": "Metals"},
  {"category_id": 182, "title": "Packaging"},
  {"category_id": 183, "title": "Petroleum"},
  {"category_id": 184, "title": "Plastics"},
  {"category_id": 185, "title": "Refrigeration and Ice"},
  {"category_id": 186, "title": "Rubber"},
  {"category_id": 187, "title": "Scientific"},
  {"category_id": 188, "title": "Security and Safety"},
  {"category_id": 189, "title": "Telecommunication Services"},
  {"category_id": 190, "title": "Textiles"},
  {"category_id": 191, "title": "Water and Waste Management"},
  {"category_id": 192, "title": "Welding"},
  {"category_id": 193, "title": "Advertising and Marketing"},
  {"category_id": 194, "title": "Advertising Agencies and Media Buyers"},
  {"category_id": 195, "title": "Creative Services"},
  {"category_id": 196, "title": "Direct Mail and Email Marketing Services"},
  {"category_id": 197, "title": "Market Research and Consulting"},
  {"category_id": 198, "title": "Online Advertising"},
  {"category_id": 199, "title": "Print, TV, Radio and Outdoor Advertising"},
  {"category_id": 200, "title": "Promotional Items"},
  {"category_id": 201, "title": "Public Relations"},
  {"category_id": 202, "title": "Search Engine Marketing and Optimization"},
  {"category_id": 203, "title": "Writing, Copywriting and Technical Writing"},
  {"category_id": 204, "title": "Agriculture and Forestry"},
  {"category_id": 205, "title": "Art Restoration"},
  {"category_id": 206, "title": "Audiovisual"},
  {"category_id": 207, "title": "Automation and Control Systems"},
  {"category_id": 208, "title": "Chemicals and Gasses"},
  {"category_id": 209, "title": "Computers"},
  {"category_id": 210, "title": "Corporate HQ"},
  {"category_id": 211, "title": "Electrical Equipment"},
  {"category_id": 212, "title": "Employment Agencies"},
  {"category_id": 213, "title": "Engineering"},
  {"category_id": 214, "title": "Entertainment"},
  {"category_id": 215, "title": "Media"},
  {"category_id": 216, "title": "Equipment Rental"},
  {"category_id": 217, "title": "Events and Event Planning"},
  {"category_id": 218, "title": "ATMs"},
  {"category_id": 219, "title": "Financial"},
  {"category_id": 220, "title": "Accounting and Bookkeeping"},
  {"category_id": 221, "title": "Banking and Finance"},
  {"category_id": 222, "title": "Business Brokers and Franchises"},
  {"category_id": 223, "title": "Check Cashing"},
  {"category_id": 224, "title": "Collections"},
  {"category_id": 225, "title": "Financial Planning and Investments"},
  {"category_id": 226, "title": "Fund Raising"},
  {"category_id": 227, "title": "Loans and Mortgages"},
  {"category_id": 228, "title": "Stock Brokers"},
  {"category_id": 229, "title": "Student Aid and Grants"},
  {"category_id": 230, "title": "Food and Beverage"},
  {"category_id": 231, "title": "Catering"},
  {"category_id": 232, "title": "Distribution"},
  {"category_id": 233, "title": "Funeral Services"},
  {"category_id": 234, "title": "Geological"},
  {"category_id": 235, "title": "Home Improvement"},
  {"category_id": 236, "title": "Architects"},
  {"category_id": 237, "title": "Carpenters"},
  {"category_id": 238, "title": "Carpet and Flooring"},
  {"category_id": 239, "title": "Contractors"},
  {"category_id": 240, "title": "Bathrooms"},
  {"category_id": 241, "title": "Deck and Patio"},
  {"category_id": 242, "title": "Sewer"},
  {"category_id": 243, "title": "Doors and Windows"},
  {"category_id": 244, "title": "Electricians"},
  {"category_id": 245, "title": "Fences, Fireplaces and Garage Doors"},
  {"category_id": 246, "title": "Hardware and Services"},
  {"category_id": 247, "title": "Heating, Ventilating and Air Conditioning"},
  {"category_id": 248, "title": "Home Appliances"},
  {"category_id": 249, "title": "Home Inspection Services"},
  {"category_id": 250, "title": "Housewares"},
  {"category_id": 251, "title": "Interior Design"},
  {"category_id": 252, "title": "Kitchens"},
  {"category_id": 253, "title": "Landscaping and Gardeners"},
  {"category_id": 254, "title": "Lighting Fixtures"},
  {"category_id": 255, "title": "Mobile Homes"},
  {"category_id": 256, "title": "Movers"},
  {"category_id": 257, "title": "Painting"},
  {"category_id": 258, "title": "Pest Control"},
  {"category_id": 259, "title": "Plumbing"},
  {"category_id": 260, "title": "Pools and Spas"},
  {"category_id": 261, "title": "Roofers"},
  {"category_id": 262, "title": "Storage"},
  {"category_id": 263, "title": "Swimming Pool Maintenance and Services"},
  {"category_id": 264, "title": "Tree Service"},
  {"category_id": 265, "title": "Upholstery"},
  {"category_id": 266, "title": "Human Resources"},
  {"category_id": 267, "title": "Import and Export"},
  {"category_id": 268, "title": "Leather"},
  {"category_id": 269, "title": "Legal"},
  {"category_id": 270, "title": "Credit Counseling and Bankruptcy Services"},
  {"category_id": 271, "title": "Immigration"},
  {"category_id": 272, "title": "Insurance"},
  {"category_id": 273, "title": "Machine Shops"},
  {"category_id": 274, "title": "Management"},
  {"category_id": 275, "title": "Manufacturing"},
  {"category_id": 276, "title": "Paper"},
  {"category_id": 277, "title": "Personal Care"},
  {"category_id": 278, "title": "Dry Cleaning, Ironing and Laundry"},
  {"category_id": 279, "title": "Hair Removal"},
  {"category_id": 280, "title": "Beauty Salons and Barbers"},
  {"category_id": 281, "title": "Manicures and Pedicures"},
  {"category_id": 282, "title": "Massage Clinics and Therapists"},
  {"category_id": 283, "title": "Piercing"},
  {"category_id": 284, "title": "Skin Care"},
  {"category_id": 285, "title": "Spas"},
  {"category_id": 286, "title": "Tanning Salons"},
  {"category_id": 287, "title": "Tattooing"},
  {"category_id": 288, "title": "Printing, Copying and Signage"},
  {"category_id": 289, "title": "Professional Cleaning"},
  {"category_id": 290, "title": "Publishing"},
  {"category_id": 291, "title": "Real Estate"},
  {"category_id": 292, "title": "Property Management"},
  {"category_id": 293, "title": "Real Estate Agents"},
  {"category_id": 294, "title": "Real Estate Appraiser"},
  {"category_id": 295, "title": "Real Estate Development and Title Companies"},
  {"category_id": 296, "title": "Apartments, Condos, and Houses"},
  {"category_id": 297, "title": "Boarding Houses"},
  {"category_id": 298, "title": "Building and Land Surveyors"},
  {"category_id": 299, "title": "Commercial Real Estate"},
  {"category_id": 300, "title": "Corporate Housing"},
  {"category_id": 301, "title": "Renewable Energy"},
  {"category_id": 302, "title": "Repair Services"},
  {"category_id": 303, "title": "Shipping, Freight, and Material Transportation"},
  {"category_id": 304, "title": "Tailors"},
  {"category_id": 305, "title": "Veterinarians"},
  {"category_id": 306, "title": "Web Design and Development"},
  {"category_id": 307, "title": "Wholesale"},
  {"category_id": 308, "title": "Social"},
  {"category_id": 309, "title": "Arts"},
  {"category_id": 310, "title": "Art Dealers and Galleries"},
  {"category_id": 311, "title": "Museums"},
  {"category_id": 312, "title": "Bars"},
  {"category_id": 313, "title": "Hotel Lounges"},
  {"category_id": 314, "title": "Jazz and Blues Cafes"},
  {"category_id": 315, "title": "Sports Bars"},
  {"category_id": 316, "title": "Wine Bars"},
  {"category_id": 317, "title": "Entertainment"},
  {"category_id": 318, "title": "Adult Entertainment"},
  {"category_id": 319, "title": "Amusement Parks"},
  {"category_id": 320, "title": "Billiard and Pool"},
  {"category_id": 321, "title": "Bingo"},
  {"category_id": 322, "title": "Bowling"},
  {"category_id": 323, "title": "Carnivals"},
  {"category_id": 324, "title": "Casinos and Gaming"},
  {"category_id": 325, "title": "Circuses"},
  {"category_id": 326, "title": "Dance Halls and Saloons"},
  {"category_id": 327, "title": "Fairgrounds and Rodeos"},
  {"category_id": 328, "title": "Go Carts"},
  {"category_id": 329, "title": "Hookah Lounges"},
  {"category_id": 330, "title": "Karaoke"},
  {"category_id": 331, "title": "Miniature Golf"},
  {"category_id": 332, "title": "Movie Theatres"},
  {"category_id": 333, "title": "Music and Show Venues"},
  {"category_id": 334, "title": "Night Clubs"},
  {"category_id": 335, "title": "Party Centers"},
  {"category_id": 336, "title": "Psychics and Astrologers"},
  {"category_id": 337, "title": "Ticket Sales"},
  {"category_id": 338, "title": "Food and Dining"},
  {"category_id": 339, "title": "Bagels and Donuts"},
  {"category_id": 340, "title": "Bakeries"},
  {"category_id": 341, "title": "Breweries"},
  {"category_id": 342, "title": "Cafes, Coffee and Tea Houses"},
  {"category_id": 343, "title": "Dessert"},
  {"category_id": 344, "title": "Ice Cream Parlors"},
  {"category_id": 345, "title": "Internet Cafes"},
  {"category_id": 346, "title": "Juice Bars and Smoothies"},
  {"category_id": 347, "title": "Restaurants"},
  {"category_id": 348, "title": "American"},
  {"category_id": 349, "title": "Barbecue"},
  {"category_id": 350, "title": "Buffets"},
  {"category_id": 351, "title": "Burgers"},
  {"category_id": 352, "title": "Chinese"},
  {"category_id": 353, "title": "Delis"},
  {"category_id": 354, "title": "Diners"},
  {"category_id": 355, "title": "Fast Food"},
  {"category_id": 356, "title": "French"},
  {"category_id": 357, "title": "Indian"},
  {"category_id": 358, "title": "Italian"},
  {"category_id": 359, "title": "Japanese"},
  {"category_id": 360, "title": "Korean"},
  {"category_id": 361, "title": "Mexican"},
  {"category_id": 362, "title": "Middle Eastern"},
  {"category_id": 363, "title": "Pizza"},
  {"category_id": 364, "title": "Seafood"},
  {"category_id": 365, "title": "Steakhouses"},
  {"category_id": 366, "title": "Sushi"},
  {"category_id": 367, "title": "Thai"},
  {"category_id": 368, "title": "Vegan and Vegetarian"},
  {"category_id": 369, "title": "Country Clubs"},
  {"category_id": 370, "title": "Wineries and Vineyards"},
  {"category_id": 371, "title": "Zoos, Aquariums and Wildlife Sanctuaries"},
  {"category_id": 372, "title": "Sports and Recreation"},
  {"category_id": 373, "title": "Athletic Fields"},
  {"category_id": 374, "title": "Baseball"},
  {"category_id": 375, "title": "Batting Ranges"},
  {"category_id": 376, "title": "Basketball"},
  {"category_id": 377, "title": "Combat Sports"},
  {"category_id": 378, "title": "Cycling"},
  {"category_id": 379, "title": "Dance"},
  {"category_id": 380, "title": "Equestrian"},
  {"category_id": 381, "title": "Football"},
  {"category_id": 382, "title": "Golf"},
  {"category_id": 383, "title": "Gun Ranges"},
  {"category_id": 384, "title": "Gymnastics"},
  {"category_id": 385, "title": "Gyms and Fitness Centers"},
  {"category_id": 386, "title": "Hockey"},
  {"category_id": 387, "title": "Outdoors"},
  {"category_id": 388, "title": "Campgrounds and RV Parks"},
  {"category_id": 389, "title": "Hiking"},
  {"category_id": 390, "title": "Hot Air Balloons"},
  {"category_id": 391, "title": "Hunting and Fishing"},
  {"category_id": 392, "title": "Rock Climbing"},
  {"category_id": 393, "title": "Skydiving"},
  {"category_id": 394, "title": "Paintball"},
  {"category_id": 395, "title": "Personal Trainers"},
  {"category_id": 396, "title": "Race Tracks"},
  {"category_id": 397, "title": "Racquet Sports"},
  {"category_id": 398, "title": "Racquetball"},
  {"category_id": 399, "title": "Tennis"},
  {"category_id": 400, "title": "Recreation Centers"},
  {"category_id": 401, "title": "Running"},
  {"category_id": 402, "title": "Skating"},
  {"category_id": 403, "title": "Snow Sports"},
  {"category_id": 404, "title": "Soccer"},
  {"category_id": 405, "title": "Sports Clubs"},
  {"category_id": 406, "title": "Stadiums and Arenas"},
  {"category_id": 407, "title": "Swimming Pools"},
  {"category_id": 408, "title": "Water Sports"},
  {"category_id": 409, "title": "Boating"},
  {"category_id": 410, "title": "Canoes and Kayaks"},
  {"category_id": 411, "title": "Rafting"},
  {"category_id": 412, "title": "Scuba Diving"},
  {"category_id": 413, "title": "Swimming"},
  {"category_id": 414, "title": "Yoga and Pilates"},
  {"category_id": 415, "title": "Transportation"},
  {"category_id": 416, "title": "Airlines and Aviation Services"},
  {"category_id": 417, "title": "Gas Stations"},
  {"category_id": 418, "title": "Parking"},
  {"category_id": 419, "title": "Public Transportation Services"},
  {"category_id": 420, "title": "Taxi and Car Services"},
  {"category_id": 421, "title": "Car and Truck Rentals"},
  {"category_id": 422, "title": "Charter Buses"},
  {"category_id": 423, "title": "Limos and Chauffeurs"},
  {"category_id": 424, "title": "Transport Hubs"},
  {"category_id": 425, "title": "Airports"},
  {"category_id": 426, "title": "Bus Stations"},
  {"category_id": 427, "title": "Heliports"},
  {"category_id": 428, "title": "Ports"},
  {"category_id": 429, "title": "Rail Stations"},
  {"category_id": 430, "title": "Travel"},
  {"category_id": 431, "title": "Cruises"},
  {"category_id": 432, "title": "Lodging"},
  {"category_id": 433, "title": "Bed and Breakfasts"},
  {"category_id": 434, "title": "Cottages and Cabins"},
  {"category_id": 435, "title": "Hostels"},
  {"category_id": 436, "title": "Hotels and Motels"},
  {"category_id": 437, "title": "Lodges and Vacation Rentals"},
  {"category_id": 438, "title": "Resorts"},
  {"category_id": 439, "title": "Tourist Information and Services"},
  {"category_id": 440, "title": "Travel Agents and Tour Operators"},
  {"category_id": 441, "title": "Geriatrics"},
  {"category_id": 442, "title": "Discount Stores"},
  {"category_id": 443, "title": "Meat and Seafood"},
  {"category_id": 444, "title": "Office Supplies"},
  {"category_id": 445, "title": "Party Supplies"},
  {"category_id": 446, "title": "Career Counseling"},
  {"category_id": 447, "title": "Construction"},
  {"category_id": 448, "title": "Notary"},
  {"category_id": 449, "title": "Photography"},
  {"category_id": 450, "title": "Translation Services"},
  {"category_id": 451, "title": "Golf Courses"},
  {"category_id": 452, "title": "Surfing"},
  {"category_id": 453, "title": "Embassies"},
  {"category_id": 454, "title": "Infrastructure"},
  {"category_id": 455, "title": "Mobile"},
  {"category_id": 456, "title": "Advertising"},
  {"category_id": 457, "title": "Asian"},
  {"category_id": 458, "title": "Food Trucks"},
  {"category_id": 459, "title": "Rest Areas"},
  {"category_id": 460, "title": "Technology"},
  {"category_id": 461, "title": "Dog Parks"},
  {"category_id": 462, "title": "International Airports"},
  {"category_id": 463, "title": "Arcades"},
  {"category_id": 464, "title": "International"},
  {"category_id": 465, "title": "Convention Centers"},
  {"category_id": 466, "title": "Optometrist"}
];
